# Generated by Django 3.2.7 on 2021-09-04 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='tittle',
        ),
        migrations.AddField(
            model_name='todo',
            name='title',
            field=models.CharField(default='title', max_length=255, verbose_name='title'),
            preserve_default=False,
        ),
    ]
